services:
  - type: web
    plan: free
    name: phishingml
    runtime: python
    buildCommand: "poetry install"
    startCommand: "python -m gunicorn phishingml.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4